blank_issues_enabled: false
contact_links:
  - name: Firechain zkEVM Docs
    url: https://docs.hermez.io
    about: Official Firechain zkEVM Documentation
  - name: Telegram Group
    url: https://t.me/thefirechain
    about: Official Firechain zkEVM Telegram Group
  - name: Discord Community
    url: https://discord.com/invite/7bYRuYbbuu
    about: Official Firechain zkEVM Discord Community
